print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $ "))
tip = int(input("How much percent tip would you like to give? 10, 12, or 15?  "))
people = int(input("How many people to split the bill? "))
tip_percent = (bill*tip)/int("100")
f_bill = str(round((bill + tip_percent)/people, 2))
print(f"Each person should pay: ${f_bill}")
print("Thanks for Using")
