print("Welcome to the tip calculator!")
bill = input("What was the total bill? $ ")
tip = input("How much percent tip would you like to give? 10, 12, or 15?  ")
people = input("How many people to split the bill? ")
tip_percent = (int(bill)*int(tip))/int("100")
f_bill = str(round((int(bill) + int(tip_percent))/int(people), 2))
print(f"Each person should pay: ${f_bill}")
print("Thanks for Using")
